image: ghcr.io/lobis/root-geant4-garfield:cxx17_ROOTv6-25-01_Geant4v10.4.3

stages:
  - pre-build
  - build
  - loadRESTLibs
  - process

before_script:
  - export USER="connector"

clang-format:
  stage: pre-build
  script:
    - echo "**$CRONJOB**"
    - echo "**$CI_SERVER_HOST**"
    - cd ${CI_PROJECT_DIR}/pipeline/clang-format/
    - ./clangformattest.sh
    # We execute only at a schedulled pipeline that defines CRONJOB variable
  only:
    variables:
      - $CRONJOB

validateLibrary:
  stage: pre-build
  script:
    - python pipeline/validateLibrary.py .
  except:
    variables:
      - $CRONJOB == "YES"

